[package]
name = "nnnoiseless"
version = "0.2.1"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/jneem/nnnoiseless"
description = "Audio denoising, derived from Xiph's RNNoise library"
autobenches = false

[lib]
bench = false

[features]
capi = ["libc"]

[[bin]]
name = "munge"
path = "src/munge.rs"
bench = false

[[bench]]
name = "sin"
harness = false

[dependencies]
num-complex = "0.2.4"
once_cell = "1.4.0"
rustfft = "3.0.1"
libc = { version = "0.2", optional = true }

[dev-dependencies]
byteorder = "1.3.4"
criterion = "0.3.3"

[package.metadata.capi]
header_name = "rnnoise"
